datawarehouse/api/kcidb/urls.py
"""Urls file."""
from django.urls import path

from . import views

urlpatterns = [
    path('data/<str:kind>', views.KCIDBView.as_view(),),
]

datawarehouse/api/urls.py
"""Urls file."""
from django.urls import path, include
from . import views

urlpatterns = [
    path('1/pipeline/<int:pipeline_id>/action', views.PipelineAction.as_view()),
    path('1/pipeline/<int:pipeline_id>/issue/record', views.PipelineIssueRecord.as_view()),
    path('1/pipeline/<int:pipeline_id>/issue/record/<int:record_id>', views.PipelineIssueRecord.as_view()),
    path('1/pipeline/<int:pipeline_id>/report', views.PipelineReport.as_view()),
    path('1/pipeline/<int:pipeline_id>', views.Pipeline.as_view()),
    path('1/pipeline/<int:pipeline_id>/patches', views.PipelinePatches.as_view()),
    path('1/pipeline/<int:pipeline_id>/jobs/<str:stage_name>', views.PipelineJobs.as_view()),
    path('1/pipeline/<int:pipeline_id>/jobs/<str:stage_name>/failures', views.PipelineFailedJobs.as_view()),
    path('1/pipeline/failures/<str:stage_name>', views.PipelineByFailures.as_view()),
    path('1/issue/<int:issue_id>/record', views.IssueRecords.as_view()),
    path('1/issue/<int:issue_id>', views.Issue.as_view()),
    path('1/issue', views.Issue.as_view()),
    path('1/issue/regex', views.IssueRegex.as_view()),
    path('1/report/missing', views.ReportMissing.as_view()),
    path('1/test/<int:test_id>/issue/record', views.TestIssueRecord.as_view()),
    path('1/test/<int:test_id>/stats', views.TestStats.as_view()),
    path('1/test/<int:test_id>', views.TestSigle.as_view()),
    path('1/test', views.TestList.as_view()),
    path('1/kcidb/', include('datawarehouse.api.kcidb.urls')),
]

datawarehouse/urls.py
# -*- coding: utf-8 -*-
# Copyright (c) 2018 Red Hat, Inc. All rights reserved. This copyrighted
# material is made available to anyone wishing to use, modify, copy, or
# redistribute it subject to the terms and conditions of the GNU General Public
# License v.2 or later.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
"""Urls file."""
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

import debug_toolbar

from datawarehouse import views
from datawarehouse.api.kcidb.views import KCIDBView

urlpatterns = [
    path('', RedirectView.as_view(url='dashboard', permanent=False)),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('confidence/<str:group>', views.confidence,),
    path('bootstrap', views.bootstrap,),
    path('cron', views.cron_run,),
    path('dashboard', views.dashboard, name='Dashboard'),
    path('details/<str:group>/<int:item_id>', views.details,),
    path('issue/list/<str:group>', views.issue_list, name='issue_list'),
    path('issue/list', RedirectView.as_view(url='list/unresolved', permanent=False)),
    path('issue/regex', views.issue_regex, name='issue_regex'),
    path('issue/<str:action>', views.issue_action,),
    path('patches/submitter/<str:group>', views.patch_get_by_submitter),
    path('patches/summary/<str:group>', views.patch_summary),
    path('patches/submitter', RedirectView.as_view(url='submitter/tested', permanent=False, query_string=True)),
    path('patches', RedirectView.as_view(url='patches/summary/tested', permanent=False)),
    path('pipeline/summary', RedirectView.as_view(url='summary/all', permanent=False)),
    path('pipeline/summary/<str:tree>', views.pipeline_summary),
    path('pipeline/failures/<str:group>', views.pipelines_by_failure),
    path('pipeline/failures', RedirectView.as_view(url='failures/all', permanent=False)),
    path('pipeline/<int:pipeline_id>', views.pipeline_get),
    path('pipeline/<int:pipeline_id>/issue', views.pipeline_issue),
    path('pipeline/<int:pipeline_id>/issue/<int:issue_record_id>/delete', views.pipeline_issue_delete),
    path('pipeline/check/all', views.pipeline_check_all),
    path('pipeline/check/<int:project_id>/<int:pipeline_id>',
         views.pipeline_check),
    path('pipeline/submit', views.pipeline_submit_webhook),
    path('pipeline/submit/<int:project_id>/<int:pipeline_id>',
         views.pipeline_submit),
    path('pipeline/submitter', views.pipelines_get_by_submitter),
    path('pipeline/running', views.pipelines_running,),
    path('metrics', RedirectView.as_view(url='metrics/all', permanent=False)),
    path('metrics/<str:tree>', views.metrics,),
    # The following url is only for compatibility.
    # It should be removed as soon as de kcidb scripts use the new endpoint.
    path('kcidb/1/data/<str:kind>', KCIDBView.as_view(),),
    path('api/', include('datawarehouse.api.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
] \
    + static(settings.MEDIA_PATH, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

datawarehouse/models/action_models.py
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2018-2019 Red Hat, Inc.

# pylint: disable=too-few-public-methods

"""Models related to actions."""

from django.db import models


class ActionKind(models.Model):
    """Model for ActionKind."""

    name = models.CharField(max_length=50)

    def __str__(self):
        """Return __str__ formatted."""
        return self.name


class Action(models.Model):
    """Model for PipelineAction."""

    created_at = models.DateTimeField(auto_now_add=True)
    kind = models.ForeignKey(ActionKind, on_delete=models.CASCADE)
    pipeline = models.ForeignKey('Pipeline',
                                 related_name='actions',
                                 on_delete=models.CASCADE)

    def __str__(self):
        """Return __str__ formatted."""
        return f'[{self.created_at}] {self.kind.name}'

datawarehouse/models/file_models.py
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2018-2019 Red Hat, Inc.

# pylint: disable=too-few-public-methods

"""Models related to the files."""

import os
from django.conf import settings
from django.db import models
from django_s3_storage.storage import S3Storage

from . import pipeline_models


S3_BUCKET = S3Storage(aws_s3_bucket_name=settings.AWS_S3_BUCKET_NAME)


def s3_directory_path(instance, filename):
    """Return path for Artifact in AWS S3."""
    # For some reason, instance.pipeline.created_at is a string instead of a datetime.
    # This hack is to workaround that. Should be fixed :)
    pipeline = pipeline_models.Pipeline.objects.get(pipeline_id=instance.pipeline.pipeline_id)
    formatted_date = pipeline.created_at.strftime("%Y/%m/%d")
    return f"{formatted_date}/{instance.pipeline.pipeline_id}/{filename}"


class Artifact(models.Model):
    """Model for Artifact."""

    file_local = models.FileField(upload_to=pipeline_models.pipeline_directory_path, null=True)
    file_remote = models.FileField(upload_to=s3_directory_path,
                                   storage=S3_BUCKET, null=True)
    pipeline = models.ForeignKey(pipeline_models.Pipeline,
                                 on_delete=models.CASCADE,
                                 related_name='artifacts')
    name = models.CharField(max_length=150)

    def __str__(self):
        """Return __str__ formatted."""
        return f'{self.name}'

    @property
    def file(self):
        """
        Dynamically decide where to store the file.

        If not on production, always locally. Otherwise, use gittree to decide.
        """
        if not settings.IS_PRODUCTION:
            return self.file_local
        if self.pipeline.gittree.internal:
            return self.file_local

        # Keep compatibility for artifacts already stored locally.
        if self.file_local:
            return self.file_local

        return self.file_remote

    @property
    def tail(self):
        """Get last 50 lines of the file."""
        try:
            return "".join(line.decode() for line in self.file.readlines()[-50:])
        except FileNotFoundError:
            return "Error: Log file not found"

    def exists(self):
        """Check if the file exists."""
        if self.file_local:
            return os.path.isfile(self.file_local.path)
        if self.file_remote:
            return S3_BUCKET.exists(self.file_remote.name)
        return False

datawarehouse/models/issue_models.py
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2018-2019 Red Hat, Inc.
"""Issue models file."""

from django.db import models


class IssueKind(models.Model):
    """Model for IssueKind."""

    description = models.CharField(max_length=200)
    tag = models.CharField(max_length=20)
    color = models.CharField(max_length=7, default='#dc3545')

    def __str__(self):
        """Return __str__ formatted."""
        return f'{self.description}'


class Issue(models.Model):
    """Model for Issue."""

    kind = models.ForeignKey(IssueKind, on_delete=models.CASCADE, null=True)
    description = models.CharField(max_length=200)
    ticket_url = models.URLField(unique=True)
    resolved = models.BooleanField(default=False)
    generic = models.BooleanField(default=False)

    def __str__(self):
        """Return __str__ formatted."""
        return f'{self.description}'

    @property
    def pipelines(self):
        """Return all pipelines linked through records."""
        return (r.pipeline for r in self.issue_records.all())


class IssueRecord(models.Model):
    """Model for IssueRecord."""

    issue = models.ForeignKey(Issue, on_delete=models.CASCADE, related_name='issue_records')
    pipeline = models.ForeignKey('Pipeline',
                                 related_name='issue_records',
                                 on_delete=models.CASCADE)
    testruns = models.ManyToManyField('TestRun', related_name='issue_records')
    bot_generated = models.BooleanField(default=False)

    def __str__(self):
        """Return __str__ formatted."""
        return f'{self.pipeline.pipeline_id} - {self.issue.description}'

    class Meta:
        """Metadata."""

        ordering = ('-id',)


class IssueRegex(models.Model):
    """Model for IssueRegex."""

    issue = models.ForeignKey(Issue, on_delete=models.CASCADE, related_name='issue_regexes')
    text_match = models.CharField(max_length=200)
    file_name_match = models.CharField(max_length=200, null=True, default=None)
    test_name_match = models.CharField(max_length=200, null=True, default=None)

    def __str__(self):
        """Return __str__ formatted."""
        return f'{self.test_name_match} - {self.file_name_match} - {self.text_match}'

datawarehouse/models/lookups.py
"""Lookup helpers."""
from django.db.models import Lookup
from django.db.models.fields import Field


@Field.register_lookup
class NotEqualLookup(Lookup):
    """Implement the SQL <> operator."""

    lookup_name = 'ne'

    def as_sql(self, compiler, connection):
        """Generate the sql query."""
        lhs, lhs_params = self.process_lhs(compiler, connection)
        rhs, rhs_params = self.process_rhs(compiler, connection)
        params = lhs_params + rhs_params
        return '%s <> %s' % (lhs, rhs), params


@Field.register_lookup
class NotInLookup(Lookup):
    """Implement the SQL NOT IN operator.

    Adapted from django.db.models.lookups. Most probably only works for simple
    lists.
    """

    lookup_name = 'not_in'

    def process_rhs(self, compiler, connection):
        """Process in a loop."""
        sqls, sqls_params = self.batch_process_rhs(compiler, connection, self.rhs)
        placeholder = '(' + ', '.join(sqls) + ')'
        return (placeholder, sqls_params)

    def get_db_prep_lookup(self, value, connection):
        """Prepare in a loop."""
        return ('%s', [self.lhs.output_field.get_db_prep_value(v, connection, prepared=True) for v in value])

    def get_prep_lookup(self):
        """Prepare in a loop."""
        return [self.lhs.output_field.get_prep_value(v) for v in self.rhs]

    def as_sql(self, compiler, connection):
        """Generate the sql query."""
        self.rhs = set(self.rhs)
        lhs, lhs_params = self.process_lhs(compiler, connection)
        rhs, rhs_params = self.process_rhs(compiler, connection)
        params = lhs_params + rhs_params
        return '%s NOT IN %s' % (lhs, rhs), params

datawarehouse/models/message_models.py
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2018-2019 Red Hat, Inc.

# pylint: disable=too-few-public-methods

"""Models related to messages."""

from django.db import models


class MessagePending(models.Model):
    """Model for MessagePending."""

    body = models.CharField(max_length=200)
    exchange = models.CharField(max_length=50)

    def __str__(self):
        """Return __str__ formatted."""
        return self.body

datawarehouse/models/report_models.py
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2018-2019 Red Hat, Inc.
"""Report models file."""

from django.db import models


class Recipient(models.Model):
    """Model for Recipient."""

    email = models.EmailField()

    def __str__(self):
        """Return __str__ formatted."""
        return f'{self.email}'


class Report(models.Model):
    """Model for Report."""

    pipeline = models.ForeignKey('Pipeline',
                                 related_name='reports',
                                 on_delete=models.CASCADE)

    subject = models.CharField(max_length=200)
    msgid = models.CharField(max_length=200, unique=True)
    body = models.TextField()
    addr_to = models.ManyToManyField(Recipient, related_name='addr_to')
    addr_cc = models.ManyToManyField(Recipient, related_name='addr_cc')
    sent_at = models.DateTimeField()
    raw = models.TextField()

    def __str__(self):
        """Return __str__ formatted."""
        return f'{self.pipeline.pipeline_id} - {self.msgid}'

datawarehouse/api/kcidb/views.py
"""Views."""
from django.http import HttpResponseBadRequest

from rest_framework.views import APIView

from datawarehouse.models import Pipeline, BuildRun, BeakerTestRun
from datawarehouse import pagination, utils
from . import serializers


TREES_TO_PUSH = [
    'arm',
    'mainline.kernel.org',
    'net-next',
    'rdma',
    'rt-devel',
    'scsi',
    'upstream-stable',
]


class KCIDBView(APIView):
    """Endpoint for kcidb data handling."""

    queryset = Pipeline.objects.none()

    config = {
        'revisions': {
            'model': Pipeline,
            'serializer': serializers.RevisionSerializer,
            'filter': {'gittree__name__in': TREES_TO_PUSH},
            'date_filter': 'started_at__gte'
            },
        'builds': {
            'model': BuildRun,
            'serializer': serializers.BuildSerializer,
            'filter': {'pipeline__gittree__name__in': TREES_TO_PUSH},
            'date_filter': 'pipeline__started_at__gte'
            },
        'tests': {
            'model': BeakerTestRun,
            'serializer': serializers.TestSerializer,
            'filter': {
                'pipeline__gittree__name__in': TREES_TO_PUSH,
                'invalid_result': False,
                },
            'exclude': {
                'result__name': 'SKIP',
                },
            'date_filter': 'pipeline__started_at__gte',
            },
    }

    def get(self, request, kind):
        """Get a list of items of the type {kind}."""
        if kind not in self.config.keys():
            return HttpResponseBadRequest(f"Not a correct kind. Must be in {list(self.config.keys())}.")

        config = self.config[kind]
        last_retrieved_id = request.GET.get('last_retrieved_id')
        min_pipeline_started_at = request.GET.get('min_pipeline_started_at')

        if not last_retrieved_id:
            return HttpResponseBadRequest("Missing 'last_retrieved_id' parameter.")

        paginator = pagination.DatawarehousePagination()

        items = config['model'].objects.filter(id__gt=last_retrieved_id, **config['filter']).order_by('id')
        if config.get('exclude'):
            items = items.exclude(**config['exclude'])
        if min_pipeline_started_at:
            try:
                min_pipeline_started_at = utils.timestamp_to_datetime(min_pipeline_started_at)
            except ValueError as exception:
                return HttpResponseBadRequest(exception)
            items = items.filter(**{config['date_filter']: min_pipeline_started_at})

        paginated_items = paginator.paginate_queryset(items, request)
        serialized_items = config['serializer'](paginated_items, many=True).data

        # Remove these keys when it's value is None.
        keys_to_remove = ['message_id', 'log_url', 'duration', 'config_url',
                          'compiler', 'path']
        for item in serialized_items:
            for key in keys_to_remove:
                if not item.get(key):
                    item.pop(key, None)

        try:
            last_item_id = paginated_items[-1].id
        except IndexError:
            last_item_id = int(last_retrieved_id)

        context = {
            'data': {
                'version': {'major': 1, 'minor': 1},
                kind: serialized_items,
            },
            'last_retrieved_id': last_item_id
        }

        return paginator.get_paginated_response(context)

datawarehouse/templates/card_issue_log.html
<div class="card shadow mb-2">
  <!-- Card Header - Accordion -->
  <a href="#collapse{{run.job.name}}" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapse{{run.job.name}}">
    <h6 class="m-0 font-weight-bold text-danger">{{run.job.stage.name|title}} - {{run.job.name}}</h6>
  </a>
  <!-- Card Content - Collapse -->
  <div class="collapse show" id="collapse{{run.job.name}}" style="">
    <div class="card-body">
      <pre ><code class="language-shell">
{{ run.log.tail }}
      </code></pre>
      </pre>
    </div>
  </div>
</div>

datawarehouse/templates/card_issue_record.html
{% if perms.datawarehouse.delete_issuerecord %}
<!-- Delete Record Modal -->
<div class="modal fade" id="deleteRecord{{ record.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteRecord{{ record.id }}Label" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
          <h5 class="modal-title" id="deleteRecord{{ record.id }}Label">Confirm action.</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          Are you sure you want to delete this issue record?
          <br/>
          <br/>
          <i>{{ record.issue.description }}</i>
          <br/>
          <br/>
          <b>This action cannot be undone.</b>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <form method="post" action="/pipeline/{{pipeline.pipeline_id}}/issue/{{record.id}}/delete">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">Confirm</button>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- End Delete Record Modal -->
{% endif %}

<div class="col-xl-12 col-md-12 mb-2">
    <div class="card border-bottom-danger shadow h-100 py-2">
    <div class="card-body">
      <div class="row no-gutters align-items-center">
        <div class="col mr-2">
          <div class="text-xs font-weight-bold text-uppercase mb-1">
              Issue Record

              {% if record.bot_generated %}
              <span class="badge badge-primary" style="background-color: #3399FFA0" title="Beep beep. This issue was recorded by a script.">Bot Generated</span>
              {% endif %}

              {% if perms.datawarehouse.delete_issuerecord %}
              <button type="button" class="close" href="#" data-toggle="modal" data-dismiss="modal" data-target="#deleteRecord{{ record.id }}">
                <span>&times;</span>
              </button>
              {% endif %}
          </div>
          <div class="h5 mb-1 font-weight-bold">
            {% include 'issue_kind_badge.html' %}
            <a href="{{record.issue.ticket_url}}">
                {{record.issue.description}}
            </a>
          </div>
          {% with test_jobs=record.testruns.all %}
          {% include 'tables/table_testrun_issue_record.html' %}
          {% endwith %}
        </div>
      </div>
    </div>
  </div>
</div>

datawarehouse/templates/card_issue_regex.html
{% load serialize %}
<div class="card border-bottom-primary shadow h-100 mb-1">
  <div class="card-body">
    <div class="row no-gutters align-items-center">
      <div class="col mr-2">
        <div class="row">
          <div class="col-xl-12">
            <label>Issue:</label>
              <a href="{% url 'issue_list' 'unresolved' %}?search={{issue_regex.issue.description}}">{{issue_regex.issue.description}}</a>
              {% if perms.datawarehouse.change_issueregex or perms.datawarehouse.delete_issueadd %}
              <button type="button" class="close" href="#" onclick="openIssueRegexModal('edit', {{ issue_regex|serialize:'IssueRegexSerializer' }})">
                <span>
                  <i class="fas fa-xs fa-pen"></i>
                </span>
              </button>
              {% endif %}
          </div>
        </div>
        <div class="row">
          <div class="col-xl-4">
            <label>Text Match: </label> {{ issue_regex.text_match }}
          </div>
          <div class="col-xl-4">
            <label>File Name Match: </label> {{ issue_regex.file_name_match }}
          </div>
          <div class="col-xl-4">
            <label>Test Name Match: </label> {{ issue_regex.test_name_match }}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

datawarehouse/templates/issues_list_actions_dropdown.html
{% if perms.datawarehouse.change_issue %}
{% load serialize %}
<span class="dropdown">
  <button class="btn btn-primary btn-sm dropdown-toggle mb-1" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Actions
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="#" onclick="editIssue({{ issue|serialize:'IssueSerializer' }})">Edit Issue</a>
    <form action="/issue/resolve" method="post">
    {% csrf_token %}
    <input type="hidden" name="redirect_to" value="/issue/list"/>
    <input type="hidden" name="issue_id" value="{{ issue.id }}"/>
    {% if issue.resolved %}
    <button class="dropdown-item btn-link" type="submit">Mark as unresolved</a>
    {% else %}
    <input type="hidden" name="resolved" value="on">
    <button class="dropdown-item btn-link" type="submit">Mark as resolved</a>
    {% endif %}
    </form>
  </div>
</span>

<script>
   function editIssue(issue) {
     document.getElementById("issue_id").value = issue['id'];
     document.getElementById("issue_description").value = issue['description'];
     document.getElementById("issue_url").value = issue['ticket_url'];
     document.getElementById("issue_kind_id").value = issue['kind']['id'];
     document.getElementById("issue_resolved").checked = issue['resolved'];
     document.getElementById("issue_generic").checked = issue['generic'];
     $('#issueModal').modal('show');
   };
</script>
{% endif %}

datawarehouse/templates/link_beaker_recipe.html
{% extends "link_beaker.html" %}
{% block url %}{{ test.recipe_url }}{% endblock %}
{% block text %}R{{ test.recipe_id }}{% endblock %}

datawarehouse/templates/link_gitlab_job.html
{% extends "link_gitlab.html" %}
{% block url %}https://xci32.lab.eng.rdu2.redhat.com/{{ pipeline.project.path }}/-/jobs/{{ jid }}{% endblock %}
{% block text %}J{{ jid }}{% endblock %}

datawarehouse/templates/modal_new_issue_regex.html
<div class="modal fade" id="issueRegexModal" tabindex="-1" role="dialog" aria-labelledby="issueRegexModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
          <h5 class="modal-title" id="issueRegexModalLabel">Create Issue Regex</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="/issue/regex" method="POST">
          {% csrf_token %}
          <div class="row">
            <div class="col-xl-12">
              <div class="form-group">
                <label for="issueid">Issue</label>
                <div class="input-group">
                  <input type="text"
                         id="issue_type_filter"
                         placeholder="Text to filter issue types in the dropdown below" />
                  <select required="required" class="form-control" id="issue_id_select" name="issue_id_select">
                  <option disabled selected>Select an option</option>
                    {% for issue in issues %}
                    <option value="{{ issue.id }}">{{ issue.kind.tag  }} | {{ issue.description }}</option>
                    {% endfor %}
                  </select>
                </div>
                {% if perms.datawarehouse.add_issue %}
                <div align="right"><a href="#" data-toggle="modal" data-dismiss="modal" data-target="#issueModal">Create new issue</a></div>
                {% endif %}
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-xl-12">
                <div class="form-group">
                  <label for="issue_regex_id">ID</label>
                  <input type="text" class="form-control" name="issue_regex_id" placeholder="Autogenerated" id="issue_regex_id" readonly>
                </div>
                <div class="form-group">
                  <label for="issue_regex_text_match">Text Match</label>
                  <input type="text" class="form-control" name="text_match" placeholder="Regex to look for in the logs" id="issue_regex_text_match" >
                </div>
                <div class="form-group">
                  <label class="optional" for="issue_regex_test_name_match">Test Name Match</label>
                  <input type="text" class="form-control" name="test_name_match" placeholder="Regex to match the test name" id="issue_regex_test_name_match" >
                </div>
                <div class="form-group">
                  <label class="optional" for="issue_regex_file_name_match">File Name Match</label>
                  <input type="text" class="form-control" name="file_name_match" placeholder="Regex to match the file name" id="issue_regex_file_name_match" >
                </div>
                <input type="hidden" id="action" name="action" value="new"/>
            </div>
          </div>
          </br>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            {% if perms.datawarehouse.delete_issueregex %}
            <div id="delete_issue_regex">
              <button type="submit" name="action" value="delete" class="btn btn-danger">Delete</button>
            </div>
            {% endif %}
            {% if perms.datawarehouse.change_issueregex or perms.datawarehouse.add_issueregex %}
            <button type="submit" class="btn btn-primary">Save</button>
            {% endif %}
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<script src="/static/js/custom.js"></script>
<script>
  const issueTypes = [
      {% for issue in issues %}
      {
          id: {{ issue.id }},
          tag: "{{ issue.kind.tag  }}",
          description: "{{ issue.description }}"
      },
      {% endfor %}
  ];

  document.getElementById('issue_type_filter').addEventListener('input', function(e) {
      filterDropdown(e.target.value, 'issue_id_select', issueTypes);
  });
</script>

datawarehouse/templates/pipeline_actions_dropdown.html
<span class="dropdown">
  <button class="btn btn-primary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Actions
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a href="/api/1/pipeline/{{pipeline.pipeline_id}}" class="dropdown-item">View in API</a>
    {% if perms.datawarehouse.add_issuerecord %}
    <a class="dropdown-item" data-toggle="modal" data-target="#issueRecordModal" href="#">Add Issue Record</a>
    {% endif %}
  </div>
</span>